-- user 테이블에 데이터 추가
INSERT INTO user (userid, user_email, user_nickname, user_pwd) VALUES (1, 'tmdvy0805@naver.com', '승표', 'asd123');
INSERT INTO user (userid, user_email, user_nickname, user_pwd) VALUES (2, 'tmdvy0801@gmail.com', '돼지밥', 'asd');

-- post 테이블에 게시글 데이터 추가
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (1, 1, 'FREE', 'KT', 'TEST1', '첫 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (2, 2, 'CHEERING', 'HANWHA', 'TEST2', '두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (3, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (4, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (5, 2, 'FREE', 'HANWHA', 'TEST5', '다섯 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (6, 2, 'FREE', 'HANWHA', 'TEST6', '여섯 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (7, 2, 'CHEERING', 'DOOSAN', 'TEST7', '일곱 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (8, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (9, 2, 'REVIEW', 'KT', 'TEST9', '아홉 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (10, 2, 'REVIEW', 'KT', 'TEST10', '열 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (11, 2, 'FREE', 'KIA', 'TEST11', '열하나 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (12, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (13, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (14, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (15, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (16, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (17, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (18, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (19, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (20, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (21, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (22, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (23, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (24, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (25, 2, 'FREE', 'KIA', 'TEST12', '열두 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (26, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (27, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (28, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (29, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (30, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (31, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (32, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (33, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (34, 1, 'REVIEW', 'DOOSAN', 'TEST3', '세 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (35, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (36, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (37, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (38, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (39, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (40, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (41, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (42, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (43, 2, 'CHEERING', 'DOOSAN', 'TEST8', '여덟 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (44, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (45, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (46, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (47, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (48, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (49, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (50, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (51, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());
INSERT INTO post (postid, userid, category, team_name, title, content, created_at) VALUES (52, 2, 'TIP', 'KIA', 'TEST4', '네 번째 게시글 내용입니다.', CURRENT_TIMESTAMP());